/**
 * Generates supabase/seed.sql: synthetic development data only (NFR-5). Run:
 * `pnpm --filter @uxie/db seed:generate`. Output is deterministic.
 *
 * - three users (instructor, student A, student B), all with the dev password below
 * - one published module with the synthetic `visible-cues` paper: published version 1, its pages,
 *   and its approved teaching guide
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse } from "yaml";
import { PagesFileSchema, TeachingGuideSchema } from "@uxie/core";

import {
  SEED_MODULE_ID as MODULE_ID,
  SEED_PAPER_ID as PAPER_ID,
  SEED_PASSWORD,
  SEED_USERS,
  SEED_VERSION_ID as VERSION_ID,
} from "./seedData";

const root = resolve(import.meta.dirname, "../../..");

const q = (s: string) => `'${s.replaceAll("'", "''")}'`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const fixture = resolve(root, "fixtures/papers/visible-cues");
const pages = PagesFileSchema.parse(
  JSON.parse(readFileSync(resolve(fixture, "pages.json"), "utf8")),
);
const guide = TeachingGuideSchema.parse(
  parse(readFileSync(resolve(fixture, "guide.yaml"), "utf8")),
);

const lines: string[] = [
  "-- GENERATED by packages/db/scripts/make-seed.ts. Synthetic development data only (NFR-5).",
  `-- Seeded accounts use the password ${q(SEED_PASSWORD)} (local stack only).`,
  "",
];

for (const u of SEED_USERS) {
  lines.push(
    `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token, email_change, email_change_token_new)`,
    `values ('00000000-0000-0000-0000-000000000000', ${q(u.id)}, 'authenticated', 'authenticated', ${q(u.email)}, extensions.crypt(${q(SEED_PASSWORD)}, extensions.gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '');`,
    `insert into auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at, last_sign_in_at)`,
    `values (${q(u.id)}, ${q(u.id)}, ${q(u.id)}, ${json({ sub: u.id, email: u.email, email_verified: true })}, 'email', now(), now(), now());`,
  );
}
lines.push(
  "",
  "-- Profiles are created by the on_auth_user_created trigger; set roles and acknowledge the notice.",
  ...SEED_USERS.map(
    (u, i) =>
      `update public.profiles set role = ${q(u.role)}, pseudonym_id = ${q(`S-seed0000${i + 1}`)}, privacy_notice_version = '2026-10-01', privacy_ack_at = now(), uxie_character = ${q(["luma", "pip", "miso"][i]!)} where id = ${q(u.id)};`,
  ),
  "",
  `insert into public.modules (id, slug, title, description, position, status) values (${q(MODULE_ID)}, 'foundations', 'Foundations of interaction', 'Seminal ideas about how people perceive and act on interfaces.', 0, 'published');`,
  `insert into public.papers (id, module_id, slug, title, authors, year, position, status) values (${q(PAPER_ID)}, ${q(MODULE_ID)}, 'visible-cues', ${q(pages.title)}, array[${pages.authors.map(q).join(", ")}], ${pages.year ?? "null"}, 0, 'draft');`,
  `insert into public.paper_versions (id, paper_id, version_no, pdf_path, pdf_sha256, page_count, token_estimate, extractor, extraction_warnings, status, published_at) values (${q(VERSION_ID)}, ${q(PAPER_ID)}, 1, ${q(`${PAPER_ID}/${VERSION_ID}.pdf`)}, 'seed', ${pages.pages.length}, ${Math.ceil(pages.pages.reduce((n, p) => n + p.text.length, 0) / 4)}, ${q(pages.extractor ?? "fixture")}, ${json(pages.warnings)}, 'published', now());`,
  `update public.papers set current_version_id = ${q(VERSION_ID)}, status = 'published' where id = ${q(PAPER_ID)};`,
  ...pages.pages.map(
    (p) =>
      `insert into public.paper_pages (version_id, page_no, text) values (${q(VERSION_ID)}, ${p.n}, ${q(p.text)});`,
  ),
  `insert into public.teaching_guides (version_id, guide, status, guide_hash, approved_at) values (${q(VERSION_ID)}, ${json(guide)}, 'approved', 'seed', now());`,
  "",
);

writeFileSync(resolve(root, "supabase/seed.sql"), lines.join("\n"));
console.log("wrote supabase/seed.sql");
